name: PRs to main
on: 
  pull_request:
    branches: [main]
    types: [closed]
jobs:
  backmerge-main-into-develop:
    if: github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
    - name: Backmerge master into develop
      run: |
          git fetch --unshallow
          git checkout develop
          git pull
          git merge --no-ff main -m "Auto backmerge main into develop"
          git push
